from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
import yt_dlp
import os
import uuid
import threading
import time
import tempfile

app = Flask(__name__)
CORS(app)

DOWNLOAD_FOLDER = "/tmp/media"
os.makedirs(DOWNLOAD_FOLDER, exist_ok=True)

# ── Cookies hardcoded ──
COOKIES_CONTENT = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.instagram.com	TRUE	/	TRUE	1813925630	datr	__YOanFSdgepfz_8x17YWn-0
.instagram.com	TRUE	/	TRUE	1810901627	ig_nrcb	1
.instagram.com	TRUE	/	TRUE	1787141653	ds_user_id	33781713660
.instagram.com	TRUE	/	TRUE	1813925653	csrftoken	s6CEIaHAPngEDBNfGltD5CVvDjgPoLot
#HttpOnly_.instagram.com	TRUE	/	TRUE	1810901627	ig_did	D4FAF04E-F43B-4EBF-8C8A-238D17C3BED4
.instagram.com	TRUE	/	TRUE	1779970455	wd	432x806
.instagram.com	TRUE	/	TRUE	1813925627	mid	ag72-wABAAFe0oP4NRrnD5Xfxqkq
#HttpOnly_.instagram.com	TRUE	/	TRUE	1810901651	sessionid	33781713660%3A58s76biSMcO06x%3A28%3AAYjHKuxzkiHjCVy54mdWx-LrphGKDUXVGBDw6FpZWA
.instagram.com	TRUE	/	TRUE	1779970455	dpr	2.5
#HttpOnly_.instagram.com	TRUE	/	TRUE	1779452064	rur	"MAZ\\05433781713660\\0541810901654:01fe47d99ffc696e45e9641ed249503d020ee873732da3c8b8a060f6141b98b24574fb3b"
"""

def get_cookie_file():
    """Write cookies to a temp file and return path"""
    tmp = tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False)
    tmp.write(COOKIES_CONTENT)
    tmp.close()
    return tmp.name

def delete_file_later(path, delay=300):
    def _delete():
        time.sleep(delay)
        if os.path.exists(path):
            os.remove(path)
    threading.Thread(target=_delete, daemon=True).start()

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-us,en;q=0.5",
    "Sec-Fetch-Mode": "navigate",
}

@app.route("/", methods=["GET"])
def home():
    return jsonify({"status": "InstaAudio API is running ✅"})


# ── AUDIO EXTRACT ──
@app.route("/extract", methods=["POST"])
def extract_audio():
    data = request.get_json()
    url = data.get("url", "").strip()

    if not url:
        return jsonify({"error": "URL is required"}), 400
    if "instagram.com" not in url:
        return jsonify({"error": "Please provide a valid Instagram URL"}), 400

    file_id = str(uuid.uuid4())
    output_path = os.path.join(DOWNLOAD_FOLDER, f"{file_id}.mp3")
    cookie_file = get_cookie_file()

    ydl_opts = {
        "format": "bestaudio/best",
        "outtmpl": os.path.join(DOWNLOAD_FOLDER, f"{file_id}.%(ext)s"),
        "postprocessors": [{
            "key": "FFmpegExtractAudio",
            "preferredcodec": "mp3",
            "preferredquality": "128",
        }],
        "quiet": True,
        "no_warnings": True,
        "cookiefile": cookie_file,
        "http_headers": HEADERS,
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            title = info.get("title", "instagram_audio")

        if not os.path.exists(output_path):
            return jsonify({"error": "Audio extraction failed. Reel may be private."}), 500

        delete_file_later(output_path)
        delete_file_later(cookie_file, delay=10)

        return jsonify({
            "success": True,
            "title": title,
            "download_url": f"/download/{file_id}",
            "filename": f"{file_id}.mp3"
        })

    except Exception as e:
        delete_file_later(cookie_file, delay=5)
        return jsonify({"error": str(e)}), 500


# ── AUDIO DOWNLOAD ──
@app.route("/download/<file_id>", methods=["GET"])
def download_file(file_id):
    path = os.path.join(DOWNLOAD_FOLDER, f"{file_id}.mp3")
    if not os.path.exists(path):
        return jsonify({"error": "File not found or expired"}), 404
    return send_file(path, as_attachment=True, download_name="instagram_audio.mp3")


# ── VIDEO EXTRACT ──
@app.route("/extract-video", methods=["POST"])
def extract_video():
    data = request.get_json()
    url = data.get("url", "").strip()

    if not url:
        return jsonify({"error": "URL is required"}), 400
    if "instagram.com" not in url:
        return jsonify({"error": "Please provide a valid Instagram URL"}), 400

    file_id = str(uuid.uuid4())
    output_path = os.path.join(DOWNLOAD_FOLDER, f"{file_id}.mp4")
    cookie_file = get_cookie_file()

    ydl_opts = {
        "format": "bestvideo+bestaudio/best",
        "outtmpl": os.path.join(DOWNLOAD_FOLDER, f"{file_id}.%(ext)s"),
        "merge_output_format": "mp4",
        "quiet": True,
        "no_warnings": True,
        "cookiefile": cookie_file,
        "http_headers": HEADERS,
    }

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            title = info.get("title", "instagram_video")

        if not os.path.exists(output_path):
            return jsonify({"error": "Video download failed. Reel may be private."}), 500

        delete_file_later(output_path)
        delete_file_later(cookie_file, delay=10)

        return jsonify({
            "success": True,
            "title": title,
            "download_url": f"/download-video/{file_id}",
            "filename": f"{file_id}.mp4"
        })

    except Exception as e:
        delete_file_later(cookie_file, delay=5)
        return jsonify({"error": str(e)}), 500


# ── VIDEO DOWNLOAD ──
@app.route("/download-video/<file_id>", methods=["GET"])
def download_video_file(file_id):
    path = os.path.join(DOWNLOAD_FOLDER, f"{file_id}.mp4")
    if not os.path.exists(path):
        return jsonify({"error": "File not found or expired"}), 404
    return send_file(path, as_attachment=True, download_name="instagram_video.mp4")


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)
